### ISSUE TITLE
Validate incorrect chars in user assigned form

### ISSUE THREAD

**Issue by davydovanton** [ossboard-org/ossboard#109]
We need to set only valid github usernames in this form: 
![screenshot 2017-03-19 02 44 14](https://cloud.githubusercontent.com/assets/1147484/24076899/f630e498-0c4d-11e7-835c-4e7932df4255.jpeg)

**Comment by charlie-wasp** [comment]
I'll take it, if it's ok :)

**Comment by davydovanton** [comment]
@charlie-wasp sorry, but @Wayzyk works on it 👍
