### ISSUE TITLE
Add ability to delete open tasks for authors

### ISSUE THREAD

**Issue by inem** [ossboard-org/ossboard#119]

**Comment by davydovanton** [comment]
what do you want to see in this feature?

**Comment by inem** [comment]
Basically I wan't to delete the ticket I created: http://www.ossboard.org/tasks/19
But it seems there's no way to.

**Comment by artofhuman** [comment]
I think we should create states. eg `opened, resolved, closed`, wdyt?

**Comment by artofhuman** [comment]
Hm, after assigning task to myself I can close or complete it ;)

**Comment by inem** [comment]
@artofhuman thanks, that was good enough solution for me!

**Comment by davydovanton** [comment]
@artofhuman we have all these states :)
https://github.com/ossboard-org/ossboard/blob/master/lib/ossboard/entities/task.rb#L22-L28

@inem you can close the task. For this you need to login, open your task, assign it to nobody and after that close this 👍
