### ISSUE TITLE
Problem with local tests

### ISSUE THREAD

**Issue by artofhuman** [ossboard-org/ossboard#140]
I have failed tests
`bundle exec rspec`

```
      Failure/Error: file = File.read(path)

      Errno::ENOENT:
        No such file or directory @ rb_sysopen - /Users/semen_pupkov/code/ossboard/public/webpack_manifest.json
```
@davydovanton mb u know about this errors ?

**Comment by davydovanton** [comment]
Hm, could you try to build assets locally and after that call rspec? For this just call `webpack` in console

**Comment by artofhuman** [comment]
`./node_modules/.bin/webpack` fixed this problem

**Comment by davydovanton** [comment]
@artofhuman can I close this issue if problem solved?
