### ISSUE TITLE
Event sourcing?

### ISSUE THREAD

**Issue by davydovanton** [ossboard-org/ossboard#160]
I think we can try to rewrite ossboard to new architecture

**Comment by kalys** [comment]
No.

- It's hard to implement and maintain.
- Ruby is not good with atomicity.
- Event sourcing is a trade-off between performance and code maintainability. Do you really need this kind of performance?

**Comment by davydovanton** [comment]
hey, thanks for  feedback.

I want to explain why I want to do it. This project is just a sandbox with small (or medium) functionality for me. It's mean that I have no idea how to develop it in a business perspective. But I can try to use any tech idea here. And event sourcing is a good thing to get some real and hardcore experience.

In this case, we can get real oss project with full event sourcing with ruby. With it, we will better understand what we need to implement in the ecosystem and what kind of problem will solve other developers.
