### ISSUE TITLE
Twitter messages: use shortener for links

### ISSUE THREAD

**Issue by davydovanton** [ossboard-org/ossboard#67]
We can use any shortener service for task links. 

For this we need:
1. select any popular shortener service
2. get information how we can send request to service
3. send request from worker
4. generate new short URL link and paste it to tweet message

### How to get request information
For example we will work with https://git.io/.

You can open site and short link. After that you'll see request params in dev tools:
![screenshot 2017-02-02 02 45 46](https://cloud.githubusercontent.com/assets/1147484/22531405/b6422fe2-e8f1-11e6-8067-f2a70685e4df.jpeg)

After that you can copy request as anything:
![screenshot 2017-02-02 02 46 16](https://cloud.githubusercontent.com/assets/1147484/22531426/c7df8fd8-e8f1-11e6-9dee-ec5f994e8bdd.jpeg)

Example for curl:
```
curl 'https://git.io/create' -H 'Origin: https://git.io' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-GB,en-US;q=0.8,en;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: */*' -H 'Referer: https://git.io/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data 'url=https%3A%2F%2Fgithub.com%2Fossboard-org%2Fossboard%2Fissues%2F65' --compressed
```

**Comment by thepry** [comment]
I can do it

**Comment by davydovanton** [comment]
@thepry cool 👍
But before it, please tell me what service you will choose, okay?
