### ISSUE TITLE
Fix styles for images in task body

### ISSUE THREAD

**Issue by davydovanton** [ossboard-org/ossboard#73]
When we create a new task with large images (from github for example) we have style error:
![screenshot 2017-02-03 03 43 56](https://cloud.githubusercontent.com/assets/1147484/22574973/a50b438a-e9c3-11e6-96b3-88ee264876ab.jpeg)

Also, you need to fix new task page:
![screenshot 2017-02-03 03 50 59](https://cloud.githubusercontent.com/assets/1147484/22575029/07fd21de-e9c4-11e6-884b-ba601bdd2c94.jpeg)

**Comment by davydovanton** [comment]
Real example: http://www.ossboard.org/tasks/28

**Comment by thesunwave** [comment]
Resolved via #80
