### ISSUE TITLE
Add missing tests

### ISSUE THREAD

**Issue by davydovanton** [ossboard-org/ossboard#94]
We need to cover some methods with tests. For this, you need to find all `TODO` comments (`git grep TODO` command in shell) and add tests for all these methods 👍 

_**P.S.:** For view specs we need to call method with `#to_s` method and match result as an HTML string_

**Comment by Neyaz** [comment]
@davydovanton Can i take it?

**Comment by davydovanton** [comment]
of course!

**Comment by Neyaz** [comment]
@davydovanton I grep TODO comments, but all of them contain not in node-modules and public folders. Can you explain how i can find those methods?

**Comment by davydovanton** [comment]
Hey, I checked this issue again and if I understand right - all `TODO` was complete.

Thanks for helping, I'll close the issue 👍
